---
title: "Trabajo1"
author: "Jeison Durango"
date: "4/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
## Paquetes usados en el análisis.
library(tidyverse)
```

```{r}
## Lectura de una base de datos tipo ".csv"
encuesta <- read.csv("encuesta1.csv", encoding = "UTF-8")
```

```{r}
encuesta <- encuesta %>% 
  mutate(Q02_FechaNac = as.Date(as.character(Q02_FechaNac), "%Y-%m-%d"))
encuesta <- encuesta %>% 
  mutate(Q07_FechaSaber11 = as.Date(as.character(Q07_FechaSaber11), "%Y-%m-%d"))
```

```{r}
##Papa por fuera del límite
encuesta$Q08_PAPA[encuesta$Q08_PAPA == 45 & !is.na(encuesta$Q08_PAPA)] <- 4.5
```

```{r}
##Q04_semestre: reemplazar NaN por promedio de cada carrera
estadisticos <- encuesta %>%
  filter(Q03_Carrera == "3 : Estadística")

promedioSemestreEstadisticos <- round(mean(estadisticos$Q04_Semestre, na.rm=TRUE), 1)
encuesta$Q04_Semestre[is.na(encuesta$Q04_Semestre)] <- promedioSemestreEstadisticos
```

```{r}
##Prueba realizada del 2000 al 2011-2: modificar escala R = 5*P
encuesta$Q05_Saber11[encuesta$Q05_Saber11 == 73] <- 73*5
```

```{r}
##q08_papa: rellenar na con promedio de cada carrera
promedioPapaEstadisticos <- round(mean(estadisticos$Q08_PAPA[estadisticos$Q04_Semestre >= 2 & estadisticos$Q04_Semestre <= 3], na.rm=TRUE), 1)
encuesta$Q08_PAPA[is.na(encuesta$Q08_PAPA) & encuesta$Q03_Carrera == "3 : Estadística"] <- promedioPapaEstadisticos
```

```{r}
##Cambiar fecha del icfes 2021 a 2019 porque está en el semestre 2
encuesta$Q07_FechaSaber11[encuesta$Q07_FechaSaber11 == as.Date("2021-08-08")] <- as.Date("2019-08-11")

##Cambiar puntaje=0 por promedio de puntajes obtenidos en ese año
icfes2019 <- encuesta %>%
  filter(Q07_FechaSaber11 >= as.Date("2019-01-01") & Q07_FechaSaber11 < as.Date("2020-01-01"))
promedioIcfes2019 <- round(mean(icfes2019$Q05_Saber11))
encuesta$Q05_Saber11[encuesta$Q05_Saber11 == 0 & encuesta$Q07_FechaSaber11 == as.Date("2019-08-08")] <- promedioIcfes2019
encuesta$Q05_Saber11[encuesta$Q05_Saber11 > 500 | encuesta$Q05_Saber11 <= 0] <- NaN
```

```{r}
##Se obtiene el valor numérico del estrato
encuesta <- encuesta %>% 
  mutate(Q10_Estrato = as.numeric(substr(Q10_Estrato, 5,5)))
```

```{r}
##q10_estrato: reemplazar "no se conoce" con el promedio de los estratos de los recursos que posee
promedioEstratoWifiPropio <- mean(encuesta$Q10_Estrato[encuesta$Q14_RecursosInformaticos..Wifi.propio == 1],  na.rm=TRUE)
promedioEstratoPortatilPropio <- mean(encuesta$Q10_Estrato[encuesta$Q14_RecursosInformaticos..Portátil.propio == 1], na.rm=TRUE)
encuesta$Q10_Estrato[is.na(encuesta$Q10_Estrato)] <- round(mean(promedioEstratoWifiPropio, promedioEstratoPortatilPropio))
```


```{r}
##Cambiar rango de porcentajes: de 0-1 a 0-100 
encuesta$Q25_PorcentArea[encuesta$Q25_PorcentArea == 0.1] <- 10
encuesta$Q27_PorcentDivisor[encuesta$Q27_PorcentDivisor == 0.5] <- 50
```


## Pregunta: ¿quiénes tienen mejor papa por carrera y género?

```{r}
## Filtros



## Filtro mujeres de estadistica.

femeninoEstadistica <- encuesta %>%
  filter(encuesta$Q01_Genero == "2 : Femenino" & encuesta$Q03_Carrera == "3 : Estadística")

## Filtro hombres de estadistica.

masculinoEstadistica <- encuesta %>%
  filter(encuesta$Q01_Genero == "1 : Masculino" & encuesta$Q03_Carrera == "3 : Estadística")

## Filtro mujeres de Sistemas.

femeninoSistemas <- encuesta %>%
  filter(encuesta$Q01_Genero == "2 : Femenino" & encuesta$Q03_Carrera == "2 : Ingeniería de sistemas e informática")

## Filtro hombres de Sistemas.

masculinoSistemas <- encuesta %>%
  filter(encuesta$Q01_Genero == "1 : Masculino" & encuesta$Q03_Carrera == "2 : Ingeniería de sistemas e informática")


## Las demas variables como son las carreras de Ingenieria Administrativa, Matematicas, Ingenieria Fisica y otras no se van a tomar en cuenta ya que la frecuencia de estas es menor comparadas con las demas (Estadistica e Ingenieria de Sistemas) y no se puede hacer un buen analisis con estas.

```


```{r}
## PROMEDIOS

## Mujeres estadistica

PromedioFemEstadis <- mean(femeninoEstadistica$Q08_PAPA)

## Hombres estadistica

PromedioMasEstadis <- mean(masculinoEstadistica$Q08_PAPA)

## Mujeres Sistemas

PromedioFemSistema <- mean(femeninoSistemas$Q08_PAPA)
## Hombres Sistemas

PromedioMasSistema <- mean(masculinoSistemas$Q08_PAPA)

```

```{r}
## Grafica

## Se crea una matriz para poder hacer la grafica de barras.

Tabla_datos <- t(matrix(cbind(PromedioFemEstadis, PromedioFemSistema, PromedioMasEstadis, PromedioMasSistema)))

Tabla_datos
  colnames(Tabla_datos) <- c("Femenino:estadistica", "Femenino:Ing.Sistemas", "Masculino:estadistica", "Masculino:Ing.Sistemas")

  
barplot(Tabla_datos,
        col = c("#469dff"),
        las = 1, 
        ylim = c(0, 5), 
        ylab = "PAPA",
        main = "P.A.P.A con relación al género y a la carrera", 
        cex.names = 0.8,
        space = c(0.7, 0.7, 0.7, 0.7))

```
## Pregunta: ¿en qué carrera están las mujeres y hombres con el mayor semestre?

```{r}
baseCarGenSem <- encuesta[,c("Q01_Genero","Q03_Carrera", "Q04_Semestre" )] # Nueva base con las variables para este analisis


baseCarGenSem$semestreIntervalo <- baseCarGenSem$Q04_Semestre
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 1.0 & baseCarGenSem$Q04_Semestre < 2.0]  <- "[1, 2)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 2.0 & baseCarGenSem$Q04_Semestre < 3.0]  <- "[2, 3)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 3.0 & baseCarGenSem$Q04_Semestre < 4.0]  <- "[3, 4)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 4.0 & baseCarGenSem$Q04_Semestre < 5.0]  <- "[4, 5)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 5.0 & baseCarGenSem$Q04_Semestre < 6.0]  <- "[5, 6)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 6.0 & baseCarGenSem$Q04_Semestre < 7.0]  <- "[6, 7)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 7.0 & baseCarGenSem$Q04_Semestre < 8.0]  <- "[7, 8)"
baseCarGenSem$semestreIntervalo[baseCarGenSem$Q04_Semestre >= 8.0 & baseCarGenSem$Q04_Semestre < 9.0]  <- "[8, 9)"

baseCarGenSem$carreras <- baseCarGenSem$Q03_Carrera
baseCarGenSem$carreras[baseCarGenSem$Q03_Carrera == "2 : Ingeniería de sistemas e informática"] <- "Ing.Sistemas"
baseCarGenSem$carreras[baseCarGenSem$Q03_Carrera == "3 : Estadística"] <- "Estadística"
baseCarGenSem$carreras[baseCarGenSem$Q03_Carrera == "1 : Matemáticas" | 
             baseCarGenSem$Q03_Carrera == "6 : Ingeniería industrial" |
             baseCarGenSem$Q03_Carrera == "5 : Ingeniería física" |
             baseCarGenSem$Q03_Carrera == "4 : Ingeniería administrativa" |
             baseCarGenSem$Q03_Carrera == "7 : Otra"] <- "Otras"

```

```{r}

tablaMasculina <- baseCarGenSem %>%
  filter(baseCarGenSem$Q01_Genero == "1 : Masculino")
tablaFemenina <- baseCarGenSem %>%
  filter(baseCarGenSem$Q01_Genero == "2 : Femenino")


masculinoCarSem <- table(tablaMasculina$carreras, tablaMasculina$semestreIntervalo)
femeninoCarSem <- table(tablaFemenina$carreras, tablaFemenina$semestreIntervalo)

palette(c("#469dff", "#46ff54", "#ff4646", "#ffcd46", "#46ffdd", "#a846ff", "#FFF798"))


 
barplot(femeninoCarSem, 
        beside = TRUE, 
        las = 1, 
        ylim = c(0, 30), 
        main = "Femenino - semestre",
        col = c(1, 2),
        legend = TRUE)


barplot(masculinoCarSem, beside = TRUE, 
        las = 1, 
        main = "Masculino - semestre", 
        ylim = c(0, 30),
        col = c(1, 2, 3),
        legend = TRUE)

```

## Pregunta: ¿las personas de menor estrato que viven en el area metropolitana creen en más conspiraciones?

```{r}
# filtro de las personas que viven en el area metropolitana

personarAreaMetro <- encuesta %>%
  filter(encuesta$Q09_EnAreaMetropolitana == 1)


## Se toman en cuenta las personas que creen en conspiraciones falsas.

#El hombre nunca llegó a la luna, es un montaje de Hollywood.

#Las vacunas no sirven y son una conspiración de las multinacionales farmacéuticas para enriquecerse.

#La tierra es hueca y en su interior existe una civilización oculta

#Los alienígenas visitaron las civilizaciones antiguas, influyeron en sus historia y construyeron los mega monumentos de la antiguedad

#Los efectos del cambio climático son naturales, y el escándalo se debe a conspiraciones de ambientalistas y de ciertos gremios económicos.

# Las ráfagas solares causan los sismos en la tierra.

## las personas que al menos crean en una de estas conspiraciones falsas será tomada como un "SI" de que si cree en conspiraciones falsas y las demas serán marcadas con "NO".
```



```{r}

## Se crea una nueva variable para guardar estos datos

personarAreaMetro$creenEnConspira[personarAreaMetro$Q15_Alunizaje == 1 | 
                    personarAreaMetro$Q18_Vacunas == 1 | 
                    personarAreaMetro$Q21_TierraHueca == 1|
                    personarAreaMetro$Q22_alienigenas == 1 |
                    personarAreaMetro$Q23_CambioClimatico == 1 |
                    personarAreaMetro$Q20_RafagasSolares == 1] <- "SI"


# Se filtran las personas que creen en conspiraciones falsas
siCreen <- personarAreaMetro %>%
  filter(personarAreaMetro$creenEnConspira == "SI")

siCreen$Q10_Estrato[siCreen$Q10_Estrato == 2] <- "Estrato 2"
siCreen$Q10_Estrato[siCreen$Q10_Estrato == 3] <- "Estrato 3"
siCreen$Q10_Estrato[siCreen$Q10_Estrato == 4] <- "Estrato 4"
siCreen$Q10_Estrato[siCreen$Q10_Estrato == 5] <- "Estrato 5"

# Se crea una tabla que guarda solo las personas que creen en conspiraciones y el estrato

tablaAreaMetro <- table(siCreen$Q10_Estrato, siCreen$creenEnConspira)

barplot(tablaAreaMetro, 
        legend = TRUE, 
        ylim = c(0, 25),
        beside = TRUE ,
        col = c(1, 2, 3, 4),
        main = "Cantidad de personas que creen en conspiraciones falsas por estrato\n Area metropolitana",
        names = "")


```
###########Jeison
# ¿Buen icfes = buen PAPA?
```{r}
plot(encuesta$Q05_Saber11, encuesta$Q08_PAPA, ylim=c(3,5))
abline(v=300, col="blue")
abline(h=3.8, col="red")
```
```{r}
buenPapaIcfes <-  nrow(encuesta %>% filter(Q05_Saber11 >= 300 & Q08_PAPA >= 3.8))
buenPapaIcfes/nrow(encuesta %>% filter(!is.na(Q05_Saber11) & !is.na(Q08_PAPA)))
```
```{r}
buenPapaIcfes2 <-  nrow(encuesta %>% filter(Q05_Saber11 <= 300 & Q08_PAPA >= 3.8))
buenPapaIcfes2/nrow(encuesta %>% filter(!is.na(Q05_Saber11) & !is.na(Q08_PAPA)))
```
#Histórico puntaje ICFES, hombres vs mujeres
```{r}
puntajesIcfes <- encuesta %>% 
  mutate(añoIcfes = format(encuesta$Q07_FechaSaber11,"%Y")) %>%
  select(Q01_Genero, Q05_Saber11, añoIcfes)

puntajesHombres <- puntajesIcfes %>% filter(Q01_Genero == "1 : Masculino") %>%
  group_by(añoIcfes) %>% summarise(puntajePromedio = mean(Q05_Saber11, na.rm=TRUE))

puntajesMujeres <- puntajesIcfes %>% filter(Q01_Genero == "2 : Femenino") %>%
  group_by(añoIcfes) %>% summarise(puntajePromedio = mean(Q05_Saber11, na.rm=TRUE))

plot(puntajesHombres$añoIcfes, puntajesHombres$puntajePromedio, type = "b",
     frame = FALSE, pch = 19, col = "red", xlab = "Año de presentación", ylab = "Puntaje",
     xlim=c(2013,2019), ylim=c(0,500))

lines(puntajesMujeres$añoIcfes, puntajesMujeres$puntajePromedio, pch = 19,
      col = "blue", type = "b", lty = 1)

legend("topleft", legend=c("Hombres", "Mujeres"),
       col=c("red", "blue"), lty = 1:1, cex=0.8)
```
###########Jeison






